CREATE DATABASE MCEISysControlAdminDB
GO
	USE MCEISysControlAdminDB
GO
CREATE TABLE [Role](
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Name] VARCHAR(30) NOT NULL,
	[Status] TINYINT NOT NULL,
	DateCreated DATETIME NOT NULL,
	DateModification DATETIME NOT NULL
);